url: http://www.vidageek.net
name: VidaGeek.net
description: 'Linux, Open-source, Programação e Produtividade'

markdown: rdiscount

permalink: /:year/:month/:day/:title/

email: contato@vidageek.net

authors: 'Breno, Ceci, Fabs, Jonas e Luiz'

plusid:
  'Jonas Abreu': 117877159392350438099
  'Luiz': 117413901265229708491

cc:
  'Jonas Abreu': 'by-sa'
  'Cecilia Fernandes': 'by-sa'
  'Luiz' : 'by-sa'
  'fabs' : 'by-sa'


feedburner:
  id: VidaGeek

google_analytics:
  account: UA-1275516-1

disqus:
  id: vidageeknet

games:
  git: 'Git'
  regex: 'RegEx'

category-names:
  conceitos: 'Conceitos'
  concorrencia: 'Concorrência'
  estrutura-dados: 'Estrutura de Dados'
  ferramentas: 'Ferramentas'
  flags: 'Flags da JVM'
  pitfalls: 'Pitfalls'
