url: http://www.vidageek.net
name: VidaGeek.net
description: 'Linux, Open-source, Programação e Produtividade'

markdown: rdiscount

permalink: /:year/:month/:day/:title/

feedburner:
  id: VidaGeek

google_analytics:
  account: UA-1275516-1

#disqus:
#  id: vidageeknet

