url: http://www.vidageek.net
name: VidaGeek.net
description: 'Linux, Open-source, Programação e Produtividade'

markdown: rdiscount

permalink: /:year/:month/:day/:title/

email: contato@vidageek.net

authors: 'Breno, Ceci, Fabs, Jonas e Luiz'

plusid:
  'Jonas Abreu': 117877159392350438099

feedburner:
  id: VidaGeek

google_analytics:
  account: UA-1275516-1

disqus:
  id: vidageeknet

