url: http://www.vidageek.net
name: VidaGeek.net
description: 'Linux, Open-source, Programação e Produtividade'

exclude: ['Rakefile', 'deploy.sh', 'temas', 'towrite', 'author-stats.sh', 'edicoes', 'generate.sh']

markdown: rdiscount

permalink: /:year/:month/:day/:title/

email: contato@vidageek.net

authors: 'Breno, Ceci, Fabs, Jonas e Luiz'

plusid:
  'Jonas Abreu': 117877159392350438099
  'Luiz': 117413901265229708491

cc:
  'Jonas Abreu': 'by-sa'
  'Cecilia Fernandes': 'by-sa'
  'Luiz' : 'by-sa'
  'fabs' : 'by-sa'


feedburner:
  id: VidaGeek

google_analytics:
  account: UA-1275516-1

disqus:
  id: vidageeknet

games:
  git: 'Git'
  regex: 'RegEx'

category-names:
  conceitos: 'Conceitos'
  concorrencia: 'Concorrência'
  estrutura-dados: 'Estrutura de Dados'
  ferramentas: 'Ferramentas'
  flags: 'Flags da JVM'
  pitfalls: 'Pitfalls'
  banco-dados: 'Banco de Dados'
  biserver: 'BI Server'
  pentaho-plugin: 'Plugins'
  kettle: 'Kettle'
  cr201307: 'Julho 2013 na Lambda3'
  cr201203: 'Março 2012 na AdaptWorks'
  cr201202: 'Fevereiro 2012 na AdaptWorks'
  cr201201: 'Janeiro 2012 na AdaptWorks'
  cr201108: 'Agosto 2011 na AdaptWorks'
  cr201107: 'Julho 2011 no AgileBrazil'
  cr201106: 'Junho 2011 na AdaptWorks'
  cr201105: 'Maio 2011 na AdaptWorks'

subsite:
  performance-java: 'Performance Java'
  conversa-rapida: 'Conversa Rápida'
  pentaho: 'Pentaho'

disqusids:
  '/performance-java/list-contains': '/list-contains.html'
  '/performance-java/use-compressed-oops': '/use-compressed-oops.html'
  '/performance-java/hashmap-100-cpu': '/hashmap-100-cpu.html'
  '/performance-java/thread-stack-size': '/thread-stack-size.html'
  '/performance-java/permsize': '/permsize.html'
  '/performance-java/xmx-xms': '/xmx-xms.html'
  '/performance-java/string-replace-all-lento': '/string-replace-all-lento.html'
  '/performance-java/jstack': '/jstack.html'
  '/performance-java/jmap-dump': '/jmap-dump.html'
  '/performance-java/visual-vm': '/visual-vm.html'
  '/performance-java/recursao-infinita': '/recursao-infinita.html'
  '/performance-java/jmap-histo': '/jmap-histo.html'
  '/performance-java/jmap-heap': '/jmap-heap.html'
  '/performance-java/por-onde-comecar-otimizar': '/por-onde-comecar-otimizar.html'
  '/performance-java/como-testar': '/como-testar.html'
  '/performance-java/otimizacao-prematura': '/otimizacao-prematura.html'
  '/performance-java/metas-otimizacao-aplicacoes-existentes': '/metas-otimizacao-aplicacoes-existentes.html'
  '/performance-java/metas-otimizacao-aplicacoes-novas': '/metas-otimizacao-aplicacoes-novas.html'
  '/performance-java/nao-otimize-sem-dados': '/nao-otimize-sem-dados.html'
  '/performance-java/como-nao-testar': '/como-nao-testar.html'
  '/performance-java/ab': '/ab.html'
  '/performance-java/jps': '/jps.html'
  '/performance-java/medias-inuteis-sem-desvio-padrao': '/medias-inuteis-sem-desvio-padrao.html'
  '/performance-java/performance-probe': '/performance-probe.html'
  '/performance-java/string-string-builder-string-buffer': '/string-string-builder-string-buffer.html'
  '/performance-java/concatenacao-string-laco': '/concatenacao-string-laco.html'
  '/performance-java/url-equals': '/url-equals.html'
  '/performance-java/quando-cachear': '/quando-cachear.html'
  '/performance-java/isole-fisicamente-ambientes': '/isole-fisicamente-ambientes.html'
  '/performance-java/xpath-mais-rapido': '/xpath-mais-rapido.html'
  '/performance-java/jps-v': '/jps-v.html'

