#! /bin/bash

let "NUM=`cat _drafts/id` + 2"

POST=_drafts/$NUM-$1.markdown

echo "---" > $POST
echo "layout: post" >> $POST
echo "title:" >> $POST
echo "author:" >> $POST
echo "---" >> $POST

echo $NUM > _drafts/id
